name: Build
on:
  workflow_dispatch:
    inputs:
      board:
        description: 'Select board to build'
        required: true
        type: choice
        options:
          - h700
          - h700_consoleonly
          - h700_rootrw
          - h700_sway
          - rgb30
          - rgb30_consoleonly
          - pi3b
          - pi3b_docker
      runner:
        description: 'Select runner type'
        required: true
        type: choice
        options:
          - github-hosted_ubuntu-24.04
          - github-hosted_ubuntu-24.04-arm
          - self-hosted_debian12-sachchat2
          - self-hosted_ubuntu-24.04
          - self-hosted_ubuntu-25.04-arm

run-name: Build for ${{ inputs.board }} on ${{ inputs.runner }}

jobs:
  build:
    runs-on: ${{ (inputs.runner == 'github-hosted_ubuntu-24.04' && 'ubuntu-24.04') || (inputs.runner == 'github-hosted_ubuntu-24.04-arm' && 'ubuntu-24.04-arm') || (inputs.runner == 'self-hosted_debian12-sachchat2' && fromJSON('["self-hosted","debian12-sachchat2"]')) || (inputs.runner == 'self-hosted_ubuntu-24.04' && fromJSON('["self-hosted","ubuntu-24.04"]')) || (inputs.runner == 'self-hosted_ubuntu-25.04-arm' && fromJSON('["self-hosted","ubuntu-25.04-arm"]')) }}
    permissions:
      contents: write
    steps:
      - name: Install deps
        if: ${{ inputs.runner == 'github-hosted_ubuntu-24.04' || inputs.runner == 'github-hosted_ubuntu-24.04-arm' }}
        run: |
          # disable mandb to save build time
          sudo mv /usr/bin/mandb /usr/bin/mandb-OFF
          sudo cp -p /bin/true /usr/bin/mandb 
          sudo rm -r /var/cache/man
          # install packages
          sudo apt update && sudo apt install -y build-essential cmake mtools

      - name: Maximize build space
        if: ${{ inputs.runner == 'github-hosted_ubuntu-24.04' || inputs.runner == 'github-hosted_ubuntu-24.04-arm' }}
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 16384
          swap-size-mb: 1024
          # remove-dotnet: 'true'
          # remove-android: 'true'
          # remove-haskell: 'true'
          # remove-codeql: 'true'
          # remove-docker-images: 'true'

      - name: Checkout main repo
        uses: actions/checkout@v5
        with:
          path: TiniLinux

      - name: Restore dl cache
        uses: actions/cache@v5
        with:
          path: TiniLinux/dl
          key: dl-cache-${{ inputs.board }}-${{ hashFiles('TiniLinux/configs/fragments/common.fragment', format('TiniLinux/configs/{0}_defconfig', inputs.board)) }}
          restore-keys: |
            dl-cache-${{ inputs.board }}-

      - name: Restore ccache
        uses: actions/cache@v5
        with:
          path: TiniLinux/.buildroot-ccache
          key: ccache-${{ inputs.board }}-${{ hashFiles('TiniLinux/configs/fragments/common.fragment', format('TiniLinux/configs/{0}_defconfig', inputs.board)) }}
          restore-keys: |
            ccache-${{ inputs.board }}-

      - name: Build
        run: |
          set -x
          cd TiniLinux
          ./make-board-build.sh configs/${{ inputs.board }}_defconfig
          cd output.${{ inputs.board }}
          # sed -i '/^BR2_CCACHE/d' .config # disable ccache because this is one time build
          make source -s
          time make -j$(nproc) -s
          cd ..

      - name: Make flashable image
        run: |
          set -x
          cd TiniLinux/output.${{ inputs.board }}
          ZIP=0 make img

          if [ "$GITHUB_REF_TYPE" == "tag" ]; then
            cd images && zip -j tinilinux-${{ inputs.board }}.img.zip tinilinux-${{ inputs.board }}.img
          fi

      - name: Archive build output
        uses: actions/upload-artifact@v7
        with:
          name: tinilinux-${{ inputs.board }}.img.zip # upload-artifact automatically zipped the file
          path: TiniLinux/output.${{ inputs.board }}/images/tinilinux-${{ inputs.board }}.img
          retention-days: 2

      - name: Create Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: TiniLinux/output.${{ inputs.board }}/images/tinilinux-${{ inputs.board }}.img.zip
          generate_release_notes: false
